/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatHomeUserGroupList: typeof import('./src/components/ChatHomeUserGroupList.vue')['default']
    ChatSilder: typeof import('./src/components/ChatSilder.vue')['default']
    ChatUser: typeof import('./src/components/ChatUser.vue')['default']
    CommunityComp: typeof import('./src/components/CommunityComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanInvite: typeof import('./src/components/ScanInvite.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanIcon: typeof import('vant/es')['Icon']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
